name: Code Coverage
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # Lint:

  Coverage:
    # runner env
    runs-on: ubuntu-latest
    # steps
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 7.2.1
      - name: Install modules
        run: pnpm install
      - name: Run Test Coverage
        run: pnpm run coverage
      - name: Upload Coverage ot Codecov
        uses: codecov/codecov-action@v3
        with:
          directory: coverage
          token: ${{secrets.CODECOV_TOKEN}}
